### ISSUE TITLE
App.config is not read when analyzing a folder of only dlls

### ISSUE THREAD

**Issue by bbronisz** [KirillOsenkov/MetadataTools#30]
Hi,

I wanted to analyze `Microsoft.Kiota.Serialization.Json.dll` and its dependencies, with some redirects to see if they work correctly. But when I've put them in one folder and redirects in `app.config` it reported issues that should be handled by those redirects, as if they were not read.
After debugging I've found that `app.config` is not taken into account but `app.exe.config` is OK.
I think that command-line option to explicitly specify config file, or report that no config files were used or better documentation on how to name the config files would be helpful. Or use any `*.config` files, instead of only `*.exe.config`.

Thanks for the tool. Unfortunately it didn't helped me to find the cause of compatibility issue :), but I'll probably use it more often in future.

**Comment by bbronisz** [comment]
It's maybe not totally related but might be: the tool reports dependencies from .NET 6:
`C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.36\System.Text.Encodings.Web.dll`
.NET 8:
`C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.36\System.Text.Encodings.Web.dll`
and .NET Framework GAC:
`C:\WINDOWS\Microsoft.NET\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll`
Could there be an option to specify framework? Or should it be read form `app.config`?

**Comment by KirillOsenkov** [comment]
are all the dlls you're analyzing public? any chance you could zip the whole directory and upload here, along with the command line used?

app.config files aren't used at runtime, they are converted to yourapp.exe.config and the runtime looks for the exe.config next to the exe of the same name. You can manually specify your app.config as a separate argument on the command line and it will be checked.

**Comment by bbronisz** [comment]
[BinaryCompat.zip](https://github.com/user-attachments/files/17939086/BinaryCompat.zip)
Simply: `checkbinarycompat`.

I know about app.config converting to app.exe.config but I was investigating a specific issue with incompatible dlls/assembly redirects which didn't have an executable that I could use. So I just copied the dlls to single folder + config to mimick the scenario where the issue happens to see what the tool would tell me.

What is the command line argument to specify my app.config? I've tried `checkbinarycompat *.dll;app.config` or `checkbinarycompat -p:*.dll;*.config` and some combinations but still don't see the `app.config` being used.

**Comment by KirillOsenkov** [comment]
Regarding the docs, we do have this:
![image](https://github.com/user-attachments/assets/18dcbaeb-6540-43b4-92f9-4d75b7fe3cea)

**Comment by KirillOsenkov** [comment]
you can run `checkbinarycompat *.dll;app.config` to include your app.config

**Comment by KirillOsenkov** [comment]
hmm, wait, that doesn't work. It is a bug indeed.

**Comment by bbronisz** [comment]
And running it from powershell it says at the end:
```txt
[general]
  The command "app.config" was not found, but does exist in the current location.
  PowerShell does not load commands from the current location by default (see 'Get-Help about_Command_Precedence').

  If you trust this command, run the following command instead:
    ➤ .\app.config
```

**Comment by KirillOsenkov** [comment]
Indeed, I see the references to 6.0.0.0 and 8.0.0.0:
![image](https://github.com/user-attachments/assets/47bf4aba-e0d5-4c50-a153-896986f55035)

I guess they're not reported as a problem because System.Text.Encodings.Web.dll is not present in the directory. The tool then resolves the 6.0.0.0 version from `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.36\System.Text.Encodings.Web.dll` and the 8.0.0.0 version from `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11\System.Text.Encodings.Web.dll`.

There's currently no way to specify the runtime to resolve from, it will attempt to resolve from all runtimes. As a workaround, if you copy either .dll to the directory, it should resolve it from there and it should participate in analysis:

```
=================================
These actual lines are new:
Assembly `System.Text.Encodings.Web` is referencing `System.Memory, Version=6.0.0.0, PublicKeyToken=cc7b13ffcd2ddd51` but found `System.Memory, Version=4.0.1.2, PublicKeyToken=cc7b13ffcd2ddd51` at `System.Memory.dll`
Assembly `System.Text.Encodings.Web` is referencing `System.Numerics.Vectors, Version=6.0.0.0, PublicKeyToken=b03f5f7f11d50a3a` but found `System.Numerics.Vectors, Version=4.1.4.0, PublicKeyToken=b03f5f7f11d50a3a` at `System.Numerics.Vectors.dll`
Assembly `System.Text.Json` is referencing `System.Text.Encodings.Web, Version=8.0.0.0, PublicKeyToken=cc7b13ffcd2ddd51` but found `System.Text.Encodings.Web, Version=6.0.0.0, PublicKeyToken=cc7b13ffcd2ddd51` at `System.Text.Encodings.Web.dll`
In assembly 'System.Text.Encodings.Web, Version=6.0.0.0, PublicKeyToken=cc7b13ffcd2ddd51': Failed to resolve member reference 'System.Void System.Numerics.Vector`1<System.UInt32>::.ctor(System.ReadOnlySpan`1<System.Byte>)' in assembly 'System.Numerics.Vectors, Version=6.0.0.0, PublicKeyToken=b03f5f7f11d50a3a'
In assembly 'System.Text.Encodings.Web, Version=6.0.0.0, PublicKeyToken=cc7b13ffcd2ddd51': Failed to resolve member reference 'System.Void System.Numerics.Vector`1<System.UInt32>::.ctor(System.Span`1<!0>)' in assembly 'System.Numerics.Vectors, Version=6.0.0.0, PublicKeyToken=b03f5f7f11d50a3a'
In assembly 'System.Text.Encodings.Web, Version=6.0.0.0, PublicKeyToken=cc7b13ffcd2ddd51': Failed to resolve member reference 'System.Void System.Numerics.Vector`1<System.UInt32>::CopyTo(System.Span`1<!0>)' in assembly 'System.Numerics.Vectors, Version=6.0.0.0, PublicKeyToken=b03f5f7f11d50a3a'
In assembly 'System.Text.Encodings.Web, Version=6.0.0.0, PublicKeyToken=cc7b13ffcd2ddd51': reference 'System.Numerics.Vectors, Version=6.0.0.0, PublicKeyToken=b03f5f7f11d50a3a' resolved from 'System.Numerics.Vectors.dll' as 'System.Numerics.Vectors, Version=4.1.4.0, PublicKeyToken=b03f5f7f11d50a3a'
=================================
```

**Comment by KirillOsenkov** [comment]
I guess when using powershell or pwsh you need to surround the argument in quotes:
`checkbinarycompat '*.dll;app.config'`

**Comment by KirillOsenkov** [comment]
OK I added a switch `-doNotResolveFromFramework`:
https://github.com/KirillOsenkov/MetadataTools/commit/159f06f9a5a6482972a4be49aff6386bd76f45da

This way you can specify the exact runtime directory yourself:
`*.dll;app.config -resolve:"C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11" -doNotResolveFromFramework`

**Comment by KirillOsenkov** [comment]
I think we got unlucky here, because System.Text.Encodings.Web.dll is not in the GAC for desktop netfx, but it is present in .NET 6.0 and 8.0 runtime directories, so we were resolving it from there. Your System.Text.Json.dll is targeting net462, but references System.Text.Encodings.Web 8.0.0.0.

Seems to be a pretty weird mishmash of dlls.

**Comment by KirillOsenkov** [comment]
Let me know if you think there's anything else I can fix to improve this situation on the tool side. Otherwise I can just publish the two fixes I made already.

**Comment by bbronisz** [comment]
I will give it a try tomorrow and let you know.
I will also rerun the test on machine with some of those DLLs in GAC as this is closer to the situation where the problem first showed up.
Thanks.

**Comment by bbronisz** [comment]
> OK I added a switch `-doNotResolveFromFramework`: [159f06f](https://github.com/KirillOsenkov/MetadataTools/commit/159f06f9a5a6482972a4be49aff6386bd76f45da)
> 
> This way you can specify the exact runtime directory yourself: `*.dll;app.config -resolve:"C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11" -doNotResolveFromFramework`

How can I specify that I want to look for dlls in GAC as I'm targeting .NET Framework?


> Hmm, your System.Numerics.Vectors.dll is so old it doesn't have the target framework attribute: ![image](https://private-user-images.githubusercontent.com/679326/390563996-1ef74c7b-4e33-4d50-a301-7071e839c640.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MjkyNzMsIm5iZiI6MTczMjgyODk3MywicGF0aCI6Ii82NzkzMjYvMzkwNTYzOTk2LTFlZjc0YzdiLTRlMzMtNGQ1MC1hMzAxLTcwNzFlODM5YzY0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQyMTIyNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjMxNWQyMDQ4OWJjMTE1MTY1MWQwY2JhNDg3ZWEzOTBhNGMxM2Y0MTE0ZDEyNmU3YzdmODNmMGNhMjEyM2IxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UTfbABHnC7QsEenVJGRjEcPoi6iyle6o6OwQAI1aboY)
> 
> it's from net4.0 I'm guessing

![image](https://github.com/user-attachments/assets/2c4e0688-e0e9-4ddf-b291-27c7a5f77223)

That was the latest version, not long ago. But yes, it was quite old.


> I think we got unlucky here, because System.Text.Encodings.Web.dll is not in the GAC for desktop netfx, but it is present in .NET 6.0 and 8.0 runtime directories, so we were resolving it from there. Your System.Text.Json.dll is targeting net462, but references System.Text.Encodings.Web 8.0.0.0.
> 
> Seems to be a pretty weird mishmash of dlls.

On the environment where this issue first occurred both versions of `System.Text.Encodings.Web` were in GAC, so it was a different weird mismash of dlls.

The only option for me would be to tell the tool to look for dlls in GAC and not in .NET 6/8/9 folders.

**Comment by bbronisz** [comment]
> OK I added a switch `-doNotResolveFromFramework`: [159f06f](https://github.com/KirillOsenkov/MetadataTools/commit/159f06f9a5a6482972a4be49aff6386bd76f45da)
> 
> This way you can specify the exact runtime directory yourself: `*.dll;app.config -resolve:"C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.11" -doNotResolveFromFramework`

I've tested the fix and passing `*.dll;app.config` works. Thanks.

**Comment by KirillOsenkov** [comment]
OK I published https://www.nuget.org/packages/checkbinarycompat/1.0.31

I made it that you can turn off resolving from GAC or from NetCore separately:

```
    -doNotResolveFromGAC       Do not resolve assemblies from GAC.
    -doNotResolveFromNetCore   Do not resolve assemblies from .NET runtime directories.
```

You want `-doNotResolveFromNetCore`

**Comment by bbronisz** [comment]
Thank you.
